-- 코드를 입력하세요
SELECT m.CART_ID
FROM (SELECT CART_ID, COUNT(NAME) AS MILK FROM CART_PRODUCTS WHERE NAME = 'Milk' GROUP BY CART_ID) m
LEFT JOIN (SELECT CART_ID, COUNT(NAME) AS YOGURT FROM CART_PRODUCTS WHERE NAME = 'Yogurt' GROUP BY CART_ID) y
ON m.CART_ID = y.CART_ID
WHERE YOGURT IS NOT NULL;