-- 코드를 입력하세요
WITH CTE AS (
    SELECT COUNT(*) AS TOTAL
    FROM USER_INFO
    WHERE YEAR(JOINED) = '2021'
)
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT u.USER_ID) AS PURCHASED_USER, ROUND(COUNT(DISTINCT u.USER_ID) / (SELECT TOTAL FROM CTE), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE s LEFT JOIN USER_INFO u
ON s.USER_ID = u.USER_ID 
WHERE YEAR(JOINED) = '2021'
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;