-- 코드를 입력하세요
WITH RECURSIVE CTE AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM CTE
    WHERE HOUR < 23
)
SELECT HOUR, IFNULL(COUNT(HOUR(DATETIME)), 0) AS COUNT
FROM CTE LEFT JOIN ANIMAL_OUTS
ON HOUR = HOUR(DATETIME)
GROUP BY HOUR
ORDER BY HOUR